class AppStrings {
  static const String courts = 'Canchas';
  static const String scheduledReservations = 'Reservas programadas';
  static const String logIn = 'Iniciar Sesión';
  static const String signUp = 'Registrarme';
  static const String email = 'Email';
  static const String password = 'Contraseña';
  static const String rememberPassword = 'Recordar contraseña';
  static const String forgotPassword = '¿Olvidaste tu contraseña?';
  static const String dontHaveAccountYet = '¿Aún no tienes una cuenta ?';
  static const String reservations = 'Reservations';
  static const String favorites = 'Favoritos';
  static const String tennis = 'Tennis';
  static const String init = 'Inicio';
  static const String register = 'Registro';
  static const String nameAndLastname = 'Nombre y apellido';
  static const String phone = 'Teléfono';
  static const String confirmPassword = 'Confirma contraseña';
  static const String alreadyHaveAnAccount = 'Ya tengo una cuenta';
  static const String addComment = 'Agregar un comentario';
  static const String reserve = 'Reservar';
  static const String setDateAndTime = 'Establecer fecha y hora';
  static const String date = 'Fecha';
  static const String initTime = 'Hora de inicio';
  static const String endTime = 'Hora de fin';
  static const String forNow = 'Por hora';
  static const String available = 'Disponible';
  static const String loading = 'Cargando';
}
